project:
  type: book
  output-dir: docs

book:
  title: "RemoteSensing_learning_diary"
  author: "Nooriza Maharani"
  date: "1/27/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - week1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

