project:
  type: book
  output-dir: docs

book:
  title: "CASA 0023"
  author: "Nooriza Maharani"
  date: "1/27/2025"
  chapters:
    - index.qmd
      unnumbered: true 
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

