project:
  type: book
  output-dir: docs

book:
  title: "CASA 0023 Learning Diary"
  author: "Nooriza Maharani"
  date: "1/27/2025"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
unnumbered-chapters: [index.qmd]
number-sections: true 
bibliography: references.bib
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

