# RS Learning Diary

---
title: "CASA023 : Remote Sensing Cities and Environments"
author: "Nooriza Maharani"
date: "January 21, 2025"
format:
  html:
    toc: true    # Enable Table of Contents
    toc-depth: 2 # Show up to level 2 headings
---

This is a Quarto book to document my learning journey in **Remote Sensing Cities and Environments** course during my time at CASA UCL 24/25, offering lessons and insights learned, applications, and reflections. The module is based on this <https://andrewmaclachlan.github.io/CASA0023/>, well for you who want to learn GIS beyond typical GIS Software, as in use R-Studio, you could also visit his other github page : <https://andrewmaclachlan.github.io/CASA0005repo/index.html>.

------------------------------------------------------------------------

## Introduction

Hi, I’m Nooriza, a student currently pursuing a Master's degree in Urban Spatial Science at UCL.

I have an academic background in Geography with a specialization in Regional Development studies and have gained substantial work experience in government consultancies in Indonesia. My work primarily focus on helping local governments or ministries with data acquisition, preparation and applied spatial analysis. My areas of expertise include thematic and basic geospatial data preparation, modeling healthcare accessibility in archipelagic regions, and supporting land-reform activities using spatial approach.

One thing that motivated me to take this course is the desire to know *how it feels to be a bird and to see the unseen.*

Feel free to explore my site to learn more about my learning experience. Hope it helps!
