---
title: "Synthetic Aperture Radar "
format:
  html:
    toc: true    # Enable Table of Contents
    toc-depth: 2 # Show up to level 2 headings
---

## Today’s lecture is exploring the sensor imagery called synthetic aperture radar. The way it functions is like a bat, where it emits sound and then the sound will be reflected by things surrounding the bat.

Its application:

a.      In for flooding

Its black and white, because it goes from low (0 values) and high values, smaller portion of signals returning back to satellite the lower the value it is.

Ø What does the flooded area appear dark in the previous image?

Ø Calm water (and smooth surfaces) reflects the radar pulses away from the sensor

Ø Rough surfaces reflect in all directions - more is sent back to the sensor

There are 2 scattering method:

a.    Rough scattering \> scattering the signals in many scattering way

b.    Volume scattering \>

c.    Double bounce scattering \>

SAR Polarization

1.   V-v

2.   V-h

## Application

## Reflection

## References
